README.md
OT: this repo is the best example of Janet's powers. In some other languages, it will be between 4 - 8 packages :-).
=> Add forgotten param to RPC server

README.md
I just copied old readmes for both projects into a spork one.
=> Add path and argparse to the README

README.md, test/suite1.janet
Sorry -- forgot to update README on my original PR.
=> Add misc/timeit and misc/set* to README (and remove a debug print from test suite)

README.md, spork/init.janet
Fix module for timeit in the README. Closes #28
=> Add temple and test to spork/init

spork/fmt.janet
This is a PR for https://github.com/janet-lang/spork/issues/27
See https://github.com/janet-lang/spork/issues/27#issuecomment-778764506 for testing details.
The gist is that comparisons were made on a relatively large number of files and the only differences detected appeared to be of the desired type.
=> Handle reader macros as part of forms

doc/test.mdz
I am sorry, but I forgot to add the docs to the new location.
=> Add docs for *-err

doc/http.mdz
=> Change def to defn in example

doc/misc.mdz
=> doc example for misc/print-table

spork/init.janet, spork/misc.janet, spork/sh.janet
Just added these two simple functions as mentioned in the Gitter/Matrix chat.
=> Add misc/randomize-array and sh/exec-slurp functions

spork/sh.janet, test/assets/17/test.file, test/suite0017.janet
Should be similar in behaviour to `mkdir -p`.  
This is a very naive implementation.
=> added copy-file and directory handling helpers

doc/test.mdz, spork/getline.janet, spork/path.janet, spork/tasker.janet, spork/temple.janet, spork/test.janet, test/suite0020.janet
As promised, I am starting to move codes from my libraries to the spork. I am starting small by adding one function to the `spork/test`. `assert-docs` checks that all the public bindings from the environment of the required path have a docstring. I have already fixed many of the docstrings in my libraries and the `spork/test` in this commit. 
I am leaving this as a draft cause I would like to check all the modules in the spork as a part of this PR if you find it worthy.
=> Add assert-docs test and fix, what it found in spork/test

doc/path.mdz, spork/path.janet, test/suite0020.janet
I discovered a special case with triggered an error in the implementation.  
Fixed it and added a test case for the previously broken case.  
Also added an example for path/relpath to the documentation
=> fixed path/relpath and added example for it in documentation

doc/misc.mdz, spork/base64.janet, spork/init.janet, test/suite0021.janet
I added it in its own module, please tell me when I should move it somewhere else in the namespace.  
I also added tests for it.
=> added base64 encoder and decoder

doc/base64.mdz, doc/misc.mdz, doc/pgp.mdz, spork/base64.janet, spork/misc.janet
I added two new mdz, which need I need to order.
=> Clean up docs after latest refactoring

spork/sh.janet
=> Use mode argument in make-new-file

spork/sh.janet
This is an attempt to address #96.
=> Make sh/copy-file create file in binary mode

test/suite-zip.janet
This PR attempts to address #97.
=> Fix zip test for Windows

spork/cjanet.janet
TBH, I have not tested the code; it is just by reading and gut feeling. Feel free to ignore it.
=> Fix typo in wrap

doc/math.mdz, spork/math.janet
Fixed typo in probability word
=> Fixed typo in probability word

spork/cjanet.janet
=> pointer types were not printed correctly

spork/test.janet
Related issue: #127
Adds a function which extends `loop` to output performance statistics after completion.
Sample usage:
```janet
(def ind (range 1000))
(timeit-loop [:timeout 1] "take" (take -500 ind))
(timeit-loop [:timeout 1] "drop" (drop 500 ind))
take 1.000s, 1.514µs/body
drop 1.000s, 1.496µs/body
```
=> Add timeit-loop

spork/cjanet.janet
Akin to `cfunction`, but indeed much more superficial. 
Part of the commit is the formatting by `spork/fmt` of the `cjanet.janet` file.
=> Add cdef directive for definning constants from C

spork/path.janet
Santa should not be separated :-D.
=> Remove forgotten debug string

spork/getline.janet
This PR is an attempt to address #167.
Hopefully it's ok or someone can point out flaws (^^;
=> Make getline respond to ctrl-k appropriately

spork/netrepl.janet
This PR is an attempt to address #160.
=> Set syspath in netrepl server handler

spork/cc.janet, spork/cjanet.janet, spork/cron.janet, spork/getline.janet, spork/http.janet, spork/httpf.janet, spork/math.janet, spork/mdz.janet, spork/misc.janet, spork/pgp.janet, spork/randgen.janet, spork/regex.janet, spork/schema.janet, spork/sh.janet, spork/tasker.janet, spork/test.janet
This PR contains almost entirely minor docstring suggestions.
Also included are a few identifier renaming suggestions.
=> Mostly tweak some docstrings

spork/netrepl.janet
This is an attempt to address #162.
=> Report when coerce-to-env fails in netrepl

spork/cron.janet, test/suite-cron.janet
Add the ability to use */n and m/n variants for ranges.
=> Cron ranges

spork/http.janet, test/suite-http.janet
This PR updates __`http/send-response`__ & __`http/read-request`__ (_`read-header`_) to avoid omitting duplicate HTTP headers when converting to/from the internal `:headers` table due to value overwriting.
_E.g.:_
```
HTTP/1.1 200 OK
Content-Type: text/html
Set-Cookie: type=biscotti
Set-Cookie: flavor=chocolate
[page content]
```
_Would only return `{"Content-Type" "text/html" "Set-Cookie" "flavor=chocolate"}` when reading, and similarly the :headers table within http/send-response had no semantics for multiple values under the same key._
---
The fix uses the same solution as for query string processing, where duplicate entries under the same key are combined into an array of values in the internal `:headers` representation.
=> Fix handling around duplicate HTTP headers

spork/declare-cc.janet
Summary: Current code uses `distinct` to generate a unique list off lflags for linking executables. This fails on macOS when linking to a framework with flags like:
["-Lfoo" "-lbar" "-lfoo" "-framework" "Cocoa" "-framework" "OpenGL"]
`distinct` generates:
@["-Lfoo" "-lbar" "-lfoo" "-framework" "Cocoa" "OpenGL"]
where `-framework` is missing for OpenGL.
=> Fix use of `distinct` on macOS lflags with `-framework`

test/suite-pm-pre-post.janet
This PR is an attempt to address #245.
Please see [the aforementioned issue](https://github.com/janet-lang/spork/issues/245) for background.
=> Clean up generated bundle from previous test run
