README.md, spork/msg.janet
I put it at the top, so when we direct someone to the correct Janet format, it is the first thing she sees in the README.
=> Add fmt and misc to readme

spork/rpc.janet
Please take this as the start of the debate, if prints should be part of this library. It is nothing critical, but they mangle test log output of one of my library :-).
=> Remove printing of logs

test/helper.janet, test/suite0.janet, test/suite1.janet, test/suite2.janet, test/suite3.janet
I have only implemented tests for fmt and misc, as low hanging fruits. Requesting a direction approval :-)
As debated in #5
=> Add test suite to fmt, misc, msg and rpc.

spork/misc.janet, test/suite1.janet
This commit adds two functions to spork/misc -- timeit, a macro for timing pieces of code using os/clock, and set*, a macro for parallel set.  Both of these were discussed with @bakpakin on gitter today so I didn't create an issue before submitting the PR.  Caveat -- I'm not a macro expert so, regardless of the fact that I did provide some working tests, you should feel free to reject based on style or any concerns you have.  Just let me know what I would need to do to clean it up.
=> Working versions of misc/timeit and misc/set*

spork/regex.janet, test/suite4.janet
An attempt to get `\a` and `\w` working.
Also some related tests.
=> Tweak some ranges in escapedchar2

spork/regex.janet
I found the comment about repetitions in `regex.janet` to be confusing: https://github.com/janet-lang/spork/blob/6f8b5a8431dba7fa2df54e6be9eea42d9a4e97d6/spork/regex.janet#L13
I took the curly braces and number to refer to `abc` in `abc{1}`, but that does not seem to be correct:
```
repl:2:> (regex/match "ab{2}" "abab")
nil
repl:3:> (regex/match "(ab){2}" "abab")
@["ab" "ab"]
```
This PR is just a tweak so that instead of `abc{1}` or `abc{1,3}`, `a{1}` and `a{1,3}` are used instead.
=> Tweak repetition comment

spork/fmt.janet
It fixes #14 by throwing an error if there is code after `:root` in `:main`.
=> Add error if there is anything after :root

spork/fmt.janet, test/suite0.janet
The PEG used by the fmt defines the rule `:value` as a sequence requiring at least one match for both `:spacing` and`:rawvalue`. This causes the formatter not to work as expected with empty forms or files containing only comments.
This PR addresses the problem by moving the initial `:spacing` from `:value` to be the initial value in `:root` and `:root2`. Tests are added to the test suite to confirm the correct behaviour.
This PR fixes #17 and fixes #19.
=> Improve spacing support in fmt

README.md, examples/temple/example.janet, examples/temple/templates/foo.temple, examples/temple/templates/hi.temple, examples/temple/templates/hop.temple, spork/temple.janet, test/suite8.janet, test/templates/hi.temple, test/templates/hop.temple
I moved the better half of the Temple's test to examples/temple/, the basic.janet, and templates I suited to test/suite8.janet. There I made one code change.
I put the whole readme before the Test part under the Temple heading.
The `temple/temple.janet` became `spork/temple.janet`.
=> Add temple

spork/netrepl.janet, test/suite8.janet
This PR:
1. creates a parser in the `netrepl/server` function body;
2. passes this to `run-context`; and
3. adds a dynamic reference to the server environment.
It also fixes a bug in `test/suite08.janet`.
At present, `netrepl/server` doesn't specify the parser to use when it calls `run-context`. This means that there is no way to manipulate the parser that parses Janet code received from the netrepl client.
The primary reason a client would want to manipulate the parser is so it can set the parser's line and column using `parser/where`. This is important for editor plugins like [Conjure](https://conjure.fun) that function as netrepl clients and send code from the editor to the netrepl server. If that code contains an error, the error message will refer to the 'line number' where the error …
=> Set run-context parser in netrepl/server

spork/netrepl.janet, test/suite8.janet, test/suite9.janet
This PR adds support for out-of-band commands to `netrepl/server` being sent with space-delimited arguments.
This PR uses a PEG to parse the message into a command and then zero or more arguments. The command is converted into a keyword and the remaining arguments are parsed into Janet values using `parse`. The PEG separates the elements by using the ` ` and `\t` characters as delimiters. This value is assigned to the value `ret` that is returned by the `getline-async` function defined in `netrepl/server` (this function is used by the `chunks` function that is passed to `run-context`).
This means that if a netrepl client sends the following message to the server:
```janet
"\xFEsource \"foobar.janet\""
```
the following value will be returned by the `chunks` function used in `run-context`: …
=> Support arguments to out-of-band commands in netrepl/server

spork/temple.janet, test/suite8.janet
This exposes the same temple templating functionality as a function that takes a template string.
This allows on-the-fly templating without creating a template file.
=> Add `temple/compile` function

doc/test.mdz, spork/test.janet, test/suite0.janet, test/suite7.janet
Sometimes it is good to be able to capture `stderr` too. It is implemented with the new `as-macro` macro as an exercise :).
This commit also fixes fmt tests, where we have not checked the result of the call. This I can move to separate PR if desirable.
If you would like to, I can also add a `suppress-err` macro akin to `suppress-stdout` implemented the same way to this PR or to separate one.
=> Add capture-err and suppress-err macros, fix fmt tests

spork/http.janet, test/suite0012.janet
Namely, I removed the dst-end argument in pre-pop, as we want it to the end anyway. And I removed the pre-pop from read-body, as the buffer is already pre-poped.
Also, fix the default port and some typos.
This PR also makes some private functions public, as developers can use them in other libraries. If it is not desirable, please let me know, and I remove these changes.
=> Fix reading request from connection in http

spork/init.janet
This PR adds `schema` module to `spork/init` for convenient import.
=> Add schema module to init for importing

spork/netrepl.janet
Currently, errors that occur during evaluation of code by the netrepl server result in only a stacktrace being sent to the client, no error message is sent. The cause of this is a change made in Janet 1.19.1 that allowed for an optional prefix parameter to be provided to `debug/stacktrace` ([changelog](https://github.com/janet-lang/janet/releases/tag/v1.19.1)). Although this parameter is optional in the sense that it does not need to be provided, if `debug/stacktrace` is called without providing a string prefix, the error message will not be printed (the stacktrace is still printed).
This PR adds an empty string prefix to the calls to `debug/stacktrace`. This [mirrors the approach](https://github.com/janet-lang/janet/commit/e8c738002bebe7bacd1b1ede3376a98b896f8f6f) taken to updating …
=> Fix error messages not printing in netrepl server

doc/htmlgen.mdz
I also have found that temple.mdz doc page is not renderable by Mendoza. And I have the feeling that it is my code that makes the problem :-).
=> Add basic documentation page for HTMLgen

spork/http.janet, test/suite0012.janet
The previous implementation would fail if \r\n\r\n weren't sent in a single packet, since it looks for it only on the boundaries of packets as returned by ev/read. This makes it look at least 4 bytes backwards – the performance difference should be minimal.
This was actually encountered using a derivation of spork/http with TLS support while communicating with an OpenWrt router (uhttpd), which output something similar to the test case, where the trailing \r\n was in its own TLS record, and read-header would skip over it. (Worse yet, with Transfer-Encoding: chunked, it also consumed the chunk data, because the closest \r\n\r\n was after the zero-length trailing chunk, making the body instead be empty.)
A test case is attached that illustrates this. Sorry if it's somewhat contrived.
=> http: Detect end-of-header in read-header even when not on a packet boundary

spork/getline.janet
Fairly minor change, but I use these a lot so it would be appreciated if they were supported as well.
=> getline: Add C-W for rubout-word, C-D delete when not EOL

examples/rawterm.janet
`rawterm/getch` returns buffer and not char.
=> Make rawterm example work with getch

.gitignore, examples/rawterm.janet
The first issue is a remnant of the old API. Adding jpm_tree to git ignored paths is an excellent thing to do in any Janet codebase, in my opinion.
=> Remove unused buffer for rawterm example, ignore jpm_tree

spork/path.janet, test/suite0020.janet
Returns the relative path between two subpaths
this should imitate the behaviour of e.g.
```bash
realpath --relative-to="a/bit/deeper/with/some/nested/dirs" "a/bit/deeper/with/other/nested/dirs"
```
I wrote a few tests for it in a new test suite.
=> added spork/relpath

doc/misc.mdz, spork/misc.janet, test/suite0001.janet, test/suite0020.janet
In the pursuit of moving my codes to spork, I have added many to the misc module. It ranges from simple mapping functions to PGP word generators.
The peg-grammar is the special addition I would like to pick for better investigation by the reviewer. I meant it as a grab bag of the peg rules and a simple mechanism to use them in your code. Presumably, we will add much more to this registry.
I also streamlined docstrings in the whole module with a simple rule: if it fits on one line, use " if it is not, use ``` on its line.
I also added prefixes to a couple of functions already in the module (with the old name as an alias, with a deprecation flag), which is out of scope for this commit but plays well with the new additions.
All the new functionality is tested and documented.
=> Move misc from marble, rename and deprecate

doc/misc.mdz, doc/temple.mdz
Both anonymous function and HTML declared as Janet are giving problems to Mendoza.
Fixes #86
=> Fix mdz build for syntax highliting

doc/data.mdz, spork/data.janet, test/suite0021.janet
Clojure contains a very useful core library called [clojure.data](https://github.com/clojure/clojure/blob/51c6d7a70912a8f65e81a8e11ae6f56c94920725/src/clj/clojure/data.clj). It contains one "exported" function: `clojure.data/diff`.
The `diff` function recursively compares the structure and contents of two data structures (list, vector, set, map) and returns a Clojure tuple with three elements:
`[things-only-in-a things-only-in-b things-in-both]`
In the case of nested maps, the comparison is recursive and the data structures are neatly partitioned into the same `[things-only-in-a things-only-in-b things-in-both]` structure, but arbitrary levels deep in the two compared Clojure maps. 
So for example, diff'ing the two Clojure maps `{:a 1 :b 2 :c {:d 3 :e 4}}` and `{:a 4 :b 2 :c {:d 3 :e 5 :f …
=> New module: `data.janet` and test suite 0021

spork/sh.janet
These three functions seem useful and were included in jpm's shell helper.
I had integrated spork/path into spork/sh/copy but otherwise the functions are nearly unchanged
=> Added copy and devnull from jpm/shutil to spork/sh

src/rawterm.c
I got the following error in clang:
```
src/rawterm.c:345:18: warning: passing 'char[18]' to parameter of type 'JanetString' (aka 'const unsigned char *') converts between pointers to integer types where one is of the unique plain 'char' type and the other is not [-Wpointer-sign]
janet_panics("invalid codepoint");
^~~~~~~~~~~~~~~~~~~
/opt/homebrew/Cellar/janet/1.25.1/include/janet/janet.h:1957:57: note: passing argument to parameter 'message' here
JANET_NO_RETURN JANET_API void janet_panics(JanetString message);
^
```
This change should fix the error and avoid undefined behavior.
=> Fix panic arg in `raw_term.c:extract_codepoint`

spork/sh.janet
I added sh/exec-slurp-all 
It has a similar behavior to sh/exec-slurp, but also collects stderr.
It also doesn't throw an error on a failed command, but returns the exit code.
=> added sh/exec-slurp-all

spork/mdz.janet, test/suite-mdz.janet
I was exporting spork/mdz in one of the projects, and assert-docs caught missing docs. This PR fixes it.
I have redone the dynamic element factory cause defglobal cannot add docs to the value. 
I added a simple test for my changes. I can add a full test of mdz when this gets merged.
=> Add documentation to the mdz, test it

spork/test.janet
With the current state, the number of tests for suites in one file accumulates, which is not ideal. And if I got it wrong, then feel free to close this.
=> Reset passed and run tests on start-suite

spork/fmt.janet
Since `loop` and `seq` are in `indent-2-forms`, perhaps their friend `tabseq` could be too?
=> Add tabseq to indent-2-forms

spork/cjanet.janet
in c they need to be mangled.
used wrong account in the previous PR, please pull this instead if you don't mind.
=> functionnames can be neat in janet

spork/cjanet.janet
i feel if this breaks do-declare, it should be fixed in do-declare... like adding a (print ";") there, but emit-statement is only called by emit-block which already emits a semicolon
=> emit-declaration: when called by emit-statement, there is a semi in caller emit-block

spork/sh.janet
If we have exec-slurp it makes sense to also have a simple exec in sh in my book.
Also fixed a bug in sh/copy
=> fixed bug in sh/copy and added sh/exec and sh/exec-fail

spork/cjanet.janet
it printed the body doubly when it wasnt empty
=> for loop was borked

spork/sh.janet, test/suite0017.janet
I imported the code from andrewchamber's [janet-shlex](https://github.com/andrewchambers/janet-shlex) (with permission).
It allows splitting a string following shell quoting rules.
=> Added shell like string splitting to spork/sh

spork/math.janet
The `math/permutations` implementation uses a non-recursive Heap's algorithm and had a typo checking if `k` was even instead of `i`, producing slightly incorrect results.
=> Fix a small bug in math/permutations.

spork/cjanet.janet
the resulting is a bit easier to read than one long line of array inits
a question of preference maybe
=> just some linebreaks

spork/argparse.janet
Currently, the custom args passing is handled as a special option, as I didn't want to add a whole new function or change the signature of the old one for this.
=> Added a way to specify custom args and a :map function to transform arguments

spork/misc.janet
on windows: tests failed due to windowsy newlines in literals, but unixy in output
=> tests failed due to windowsy newlines in literals, but unixy in output

spork/argparse.janet
:map was applied multiple times, it is now only applied at the end to avoid this.
Also :map is applied to value directly instead of handling :accumulate separately
=> Added better documentation for :map in spork/argparse and fixed bug when applying the func

spork/misc.janet, test/suite0020.janet
As discussed in https://github.com/janet-lang/spork/pull/136 here's map-keys-flat in it's own PR.
=> added misc/map-keys-flat to map keys without recursing

spork/test.janet
Does exactly what the title says.
I originally wanted to expand `spork/test` a bit here too, but decided to split this first simple one.
Should be easier to discuss.
=> don't print colored output in test when not (os/isatty)

spork/misc.janet
`misc/map-keys` was broken for cases like `(misc/map-keys |(string $0) {:test [1 2 3]})` in which it produced `@{2 3 "test" 1}` or even failed with inputs like `{:test [1 2 3 4]}`.
This should fix that by ensuring values are always left as is. I also disabled the default recursion as I think that is quite an unexpected behavior, but I left a flag to enable recursion.
This changes the function signature of misc/map-keys, but I think no one uses this function, as anyone having a value with an array in it would discover this bug pretty fast.
As this was merged from pepe's marble into spork: have a ping: @pepe
=> fixed misc/map-keys handling of array values

bin/janet-format, spork/fmt.janet
This is a configuration that will be helpful for DSLs, there's already one used in `project.janet` that uses `phony` and friends. There's a peg `(peg/compile ~(+ "with-" "def" "if-" "when-")` that tries to solve this problem but it is not enough in some situations. The current version is an initial draft, other improvements that may follow:
- More configuration options, but I can't think of any.
- More intelligent discovery of the configuration file, for example when inside a project tree, the search could be traversed to every parent directory until the `project.janet` file is found, then it stops.
Example config file .janet-config.jdn
```
["phony"]
```
I formatted the files I touched in a separate commit, I hope it's alright, let me know if not.
The configuration option probably needs a …
=> Add fmt configuration

spork/misc.janet
- Adds `binary-search` and `binary-search-by` to efficiently locate a value / insert position within a sorted tuple or array. These are implemented as macros so that primitive comparators will compile directly to vm ops.
- Updates `insert-sorted` and `insert-sorted-by` to utilize these macros.
- `misc.janet` has been run through `fmt/format-file`.
No new tests have been added, the current tests for `insert-sorted` and `insert-sorted-by` are likely sufficient.
=> add binary-search macros

spork/math.janet, test/suite-math.janet
Related: #147 
- Adds `math/factor`:
```
(math/factor n)
Returns an array containing the prime factors of `n`.
```
- Speeds up `miller-rabin-prp?`
=> Add `math/factor`

spork/data.janet, test/suite0021.janet
Added additional tests to /test/suite0021.janet , applying to `spork/data/diff`.
This revealed bugs in the way `diff` was handling larger, more deeply-nested structures.
While fixing bugs, simplified `diff`'s logic which allowed eliminating several small "helper" functions. The eliminated function calls *probably* improve performance of `diff`, but I haven't benchmarked before/after.
All tests, including newly-added ones, now pass.
=> Code quality improvements, bugfixes, additional tests for `spork/data`

spork/argparse.janet
=> allow cfunctions in argparse :map

spork/ev-utils.janet
There is a crash when using pmap-full because the list of fibers passed to "join" is an array and not a table.
The fix aligns pmap-full implementation to pcall.
```
error: bad slot #0, expected table, got <array 0x600002C65C40>
in table/clear [src/core/table.c] on line 411
in drain-fibers [/Users/mraveloarinjaka/projects/sandbox/aoc2023/jpm_tree/lib/spork/ev-utils.janet] on line 35, column 3
in join [/Users/mraveloarinjaka/projects/sandbox/aoc2023/jpm_tree/lib/spork/ev-utils.janet] on line 56, column 10
in pmap-full [/Users/mraveloarinjaka/projects/sandbox/aoc2023/jpm_tree/lib/spork/ev-utils.janet] (tailcall) on line 84, column 3
```
=> create a table instead of an array to hold the fibers in pmap-full

spork/randgen.janet, test/suite-randgen.janet
This PR adds a file `suite-randgen.janet` to test randgen.
A docstring was also added to randgen's `get-rng` as part of satisfying an `assert-docs` form in the test file.
=> Add some tests for randgen

.github/workflows/test.yml
Removes friction from PR contributions and automatically triggers the linters/checks without first getting "approval" from repo maintainer.
=> CI/CD feature: Remove "This workflow requires approval from a maintainer"

spork/stream.janet
* `spork/stream/lines` ignored separator argument. Now, it is respected.
* `separator` argument in `spork/stream/lines` is now a named argument.
* minor issues with docstring in `spork/stream` functions are fixed.
* supervisor argument is added to `spork/stream/lines-channel`. The supervisor channel is notified of stream errors.
* closing the channel returned by `spork/stream/lines-channel` finishes the tasks that feed the channel.
=> Fix `spork/stream/lines`. Refine `spork/stream` functions.

spork/randgen.janet, test/suite-randgen.janet
This adds a Gaussian sampler that exposes a similar interface to `spork/rand-uniform`, that is:
- can be called without args `(rand-gaussian)` for a single standard Gaussian sample
- can be called with args `(rand-gaussian 5 0.1)` for a single Gaussian sample with specified parameters
- can be used to generate `N` samples with the `sample-n` function, using `(sample-n |(rand-gaussian 5 0.1) 100)`
- does not leave any state pending (no fiber used) at the expense of wasting half the entropy exracted from the RNG device (does janet runtime rely on OS RNG entropy pool?)
=> Feature: Add a Gaussian sampler

spork/base64.janet
This PR contains a suggestion to change the current argument name for the `sextets->octets` function in `base64.janet`.
=> Change arg name for sextets->octets

spork/cc.janet
As discussed in #191, `cc.janet` does not work correctly when compiling on macOS. This PR addresses these problems by:
1. using `-Wl,rpath,` rather than `-Wl,rpath=`
2. not using `-Wl,-Bstatic` and `-Wl,-Bdynamic` on macOS
3. disabling  `-Wl,--start-group` and `-Wl,--end-group` by default on macOS
4. enabling dynamic lookup for undefined symbols on macOS
I'm using a vendored version of this file successfully to compile Janet libraries on macOS as part of [Arnie](https://github.com/pyrmont/arnie). This fixes #191.
=> Fix compilation on macOS

spork/init.janet
This fixes, among other things, errors encountered while running `mdz build` in the project root.
Sent From My Pixel 6 Pro
=> Update init.janet to reflect native-ification of base64 module

spork/http.janet
`http` contains a number of docstrings that look like they should be long strings but aren't. For example, `http/request`.
Current output of `(doc http/request)` at the REPL:
```console
Janet 1.36.0-dev-c82fd106 linux/x64/gcc - '(doc)' for help
repl:1:> (import spork/http)
@{_ @{:value <cycle 0>} http/cookie-grammar @{:private true} http/cookies @{:private true} http/logger @{:private true} http/middleware @{:private true} http/query-string-grammar @{:private true} http/read-body @{:private true} http/read-request @{:private true} http/read-response @{:private true} http/request @{:private true} http/request-peg @{:private true} http/response-peg @{:private true} http/router @{:private true} http/send-response @{:private true} http/server @{:private true} http/server-handler @{:private …
```
=> Fix broken multi-line docstrings in `spork/http`

spork/temple.janet, test/suite-temple.janet
=> Add capture* functions to temple module

spork/http.janet
Also remove unused head-size and format the module code.
=> Fix reading text/stream content type

spork/math.janet
There was [a CI error related to #203](https://github.com/janet-lang/spork/actions/runs/12004487043/job/33459550150?pr=203).
My current guess is that due to [recent changes in hashing in janet](https://github.com/janet-lang/janet/issues/1520), the order in which the key-value pairs are evaluated has changed.
So before may be: https://github.com/janet-lang/spork/blob/44e26016352a66fd49470eb2170aa111d887484b/spork/math.janet#L360-L363
worked fine because luckily the `(def m ...)` happened before the use of `m` for the value associated with `:b`.
This PR just moves the `def` form out of the struct.
=> Define symbol early enough for use in math

spork/netrepl.janet
Currently, [the following exists in netrepl.janet](https://github.com/janet-lang/spork/blob/deda9658e84477be3b4fa33150f7c9e282a1e3bd/spork/netrepl.janet#L245):
```janet
(def f (go-nursery nurse flusher))
```
It looks like it may be safe to replace it with:
```janet
(go-nursery nurse flusher)
```
as there are no other relevant references to `f`.
This PR is a suggestion to make that replacement.
---
It appears `(def f ...)` was needed at some point before, but when [this change](https://github.com/janet-lang/spork/commit/a3d9d1ba67abb9af28081b437e385ab079ec11cc#diff-6325e8f118a5017cf80fa18326395289464d772b47c88b045cd2d8f960f49727R240) was made (may need to scroll up depending on browser settings), the code:
```janet
(edefer (ev/cancel f "form evaluated")
```
was replaced with:
```janet …
```
=> Remove unused def

doc/api/generators.mdz
This PR contains a change to the markup in [doc/api/generators.mdz](https://github.com/janet-lang/spork/blob/7fd743ac09e857fe0ebd333bd7a56cd0df3876c3/doc/api/generators.mdz) as an attempt to address #206.
It's a simple substitution of `em` for `i`.
=> Tweak markup to address #206

src/cmath.c
Thanks to the fixes and comments from @chamaeleon I think this is the final change to get Spork building and the tests working on Windows ARM64 - see #209
=> final fix for getting spork building and tests working on Windows ARM64

bin/janet-pm, man/janet-pm.1
This PR is a mostly a suggestion to sync the help output for `janet-pm` with the man page content.
`janet-pm.1` (man page):
* added `env name` info
`janet-pm` (help output):
* removed `JANET_LIBPATH` entry
* removed `JANET_MANPATH` entry
Additionally included were:
* Some grammar and punctuation tweaks
* Some line length modification of the help output for fitting on narrower terminals
=> Sync janet-pm help and man page coutent

test/suite-declare-cc.janet, test/suite-pm.janet, test/suite-pmfull.janet
This PR is a suggestion to modify some paths in a few `import` and `assert-docs` calls.
The background is that in 2d4638cf, running some of the test files gives errors like:
```
$ janet test/suite-pm.janet 
error: could not find module spork/pm:
/home/user/.local/lib/janet/spork/pm.jimage
/home/user/.local/lib/janet/spork/pm.janet
/home/user/.local/lib/janet/spork/pm/init.janet
/home/user/.local/lib/janet/spork/pm.so
in require-1 [boot.janet] (tail call) on line 3125, column 20
in assert-docs [spork/test.janet] on line 149, column 27
in thunk [test/suite-pm.janet] (tail call) on line 9, column 1
```
```
$ SPORK_TEST_ALL_PACKAGES=1 janet test/suite-pmfull.janet 
error: could not find module spork/pm:
/home/user/.local/lib/janet/spork/pm.jimage
/home/user/.local/lib/janet/spork/pm.janet …
```
=> Tweak some import and assert-docs paths

spork/pm.janet
=> Make deftemplate and opt-ask public

spork/cc.janet
Currently using :pkg-config-libs with declare-executable gives the following error:
error: bad slot #0, expected array, got <tuple 0x7C2127E0CE00>
in array/concat [src/core/array.c] on line 250
in pkg-config [/home/ifreund/.local/lib/janet/spork/cc.janet] (tail call) on line 749, column 3
in target [/home/ifreund/.local/lib/janet/spork/declare-cc.janet] on line 828, column 11
in edefer [/home/ifreund/.local/lib/janet/spork/build-rules.janet] on line 118, column 22
in _while [/home/ifreund/.local/lib/janet/spork/build-rules.janet] on line 112, column 7
in worker [/home/ifreund/.local/lib/janet/spork/build-rules.janet] on line 105, column 5
in defer [/home/ifreund/.local/lib/janet/spork/build-rules.janet] on line 19, column 11
in wait-for-fibers …
=> cc/pkg-config: handle tuple *cflags* and *ldflags*

spork/declare-cc.janet, test-project/hello/init.janet, test-project/project.janet, test-project/test/test-hello.janet, test/suite-pm-pre-post.janet
Adding these extra steps allows more user control of the build process for complicated builds, including pre/post steps for build, install, test and clean.
This also addresses #225, so that `prebuild` is only run before `build`.
Also removes redundant call to `build` in the `install` hook since Janet's core install hook calls `build` first as well. Having this in `spork` resulted in two calls to `build` when `janet-pm install` was run.
=> Brief: add more pre/post steps for janet-pm building

spork/cc.janet
Summary: If a native executable depends on a module that includes native code, and that module could also depend on a static library, then all the extra libs added from that module (via the `foo.meta.janet` file) need to be included in the same --start-group/--end-group along with janet.a and the native code from the executable.
in this link line, from my re-janet library, you can see the linker adding "-lpcre2-8" that comes from the `jre.meta.janet` file. But is is before the `--start-group` and therefore causes missing symbols on Linux.
```
g++ -std=c++11 -O2 -g -I/home/bob/dev/janet/include -L/home/bob/dev/janet/lib/janet -L/home/bob/dev/janet/lib -o _build/release/jgrep ./_build___release___jgrep.c.o -rdynamic -pthread -L/home/bob/dev/janet/lib/janet/jre -lpcre2-8 -Wl,--start-group …
```
=> Brief: Fix smart-libs when executable depends on native module.

spork/declare-cc.janet
`cc/out-path` uses the dynamic binding associated with `*build-dir*` to associate the returned path with the build directory. However, this value will not be set correctly if called before the build environment is set up. This is why if you create a quickbin, you’ll see a stray object file.
This PR moves a call to `cc/out-path` to after the build environment is properly configured.
=> Move binding of object path to inside build environment

spork/pm.janet
Another POSIX muscle memory catch. I am enjoying the usage of special environments a lot!
=> Fix PATH separator in ps activate script

spork/declare-cc.janet
This PR is a follow-up to the discussion starting [here](https://github.com/janet-lang/spork/pull/230#issuecomment-3334372279).
As part of #230, the lone use of `last-line` was removed from the definition of `declare-binscript`.  This PR is a suggestion to remove the definition of `last-line` since it does not appear to be used any more.
=> Remove unused code
